# DataSource Configuration
management:
  endpoints:
    web:
      exposure:
        include: health
      cors:
        allowed-origins: "*"
spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30

  # Flyway Configuration
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration
    user: postgres
    password: postgres
    enabled: false
axon:
  serializer:
    ## xstream is not compatible anymore with jdk17+
    general: jackson
  axonserver:
    enabled: false

#axoniq:
#  console:
#    application-name: Awesome-Microservice
#    credentials: <token> #https://console.axoniq.io/
#    dlq-mode: NONE

application:
  debug:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
      cors:
        allowed-origins: "http://localhost:8081"
        allowed-methods: GET,POST,OPTIONS

notifications:
  enabled: true

createcatalogentry:
  fakeevents:
    enabled: true